In [ ]:
import datetime as dt
tanggal = dt.date.today()
mahasiswa = ["Muhamad Aulia Rifki", "2023071030", "Informatika", "Desain Analisis Algoritma", str(tanggal), "Universitas Pembangunan Jaya" ]
print(mahasiswa)

['Muhamad Aulia Rifki', '2023071030', 'Informatika', 'Desain Analisis Algoritma', '2024-09-19', 'Universitas Pembangunan Jaya']


In [ ]:
print("Nim", mahasiswa[1])
print("Universitas", mahasiswa[5])

Nim 2023071030
Universitas Universitas Pembangunan Jaya


In [ ]:
mahasiswa[1:3]

['2023071030', 'Informatika']

In [ ]:
print("NIM", mahasiswa[1:2])

NIM ['2023071030']


In [ ]:
print("Prodi", mahasiswa[2:3])

Prodi ['Informatika']


In [ ]:
print("Mata Kuliah Tanggal Berapa", mahasiswa[4:5])

Mata Kuliah Tanggal Berapa ['2024-09-19']


In [ ]:
for aMahasiswa in mahasiswa:
    print(aMahasiswa + " UPJ")

Muhamad Aulia Rifki UPJ
2023071030 UPJ
Informatika UPJ
Desain Analisis Algoritma UPJ
2024-09-19 UPJ
Universitas Pembangunan Jaya UPJ


In [ ]:
UPJ=("Universitas","Pembangunan","Jaya")
UPJ[0:]

('Universitas', 'Pembangunan', 'Jaya')

In [ ]:
nested_tuple=(100,(200,400,600),300,(400,800))
nested_tuple[0]

100

In [ ]:
print(nested_tuple[1])

(200, 400, 600)


In [ ]:
print(nested_tuple[2])

300


In [ ]:
print(nested_tuple[3])

(400, 800)


In [ ]:
bin_colors ={
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [ ]:
bin_colors.get('approved_color')

'Green'

In [ ]:
bin_colors['approved_color']

'Green'

In [ ]:
Latihan ={
    "Nama": "Muhamad Aulia Rifki",
    "Nim": "2023071030",
    "Prodi": "Informatika",
    "Universitas": "UPJ"
}
print(Latihan)

{'Nama': 'Muhamad Aulia Rifki', 'Nim': '2023071030', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [ ]:
yellow = {"dandellion","leaves","fire hydrant"}
red = {'leaves',"fire hydrant","blood"}
print(yellow|red)
print(yellow&red)

{'fire hydrant', 'leaves', 'dandellion', 'blood'}
{'fire hydrant', 'leaves'}


In [6]:
import pandas as pd
df = pd.DataFrame([
    ['1','Informatika', 50, 30, 20],
    ['2','Sistem Informasi', 55, 30, 25],
    ['3','Teknik Sipil', 40, 30, 10]
]
)

In [7]:
df.columns = ['No', 'Prodi', 'Mahasiswa', 'Lakilaki', 'Perempuan']
df

No             Prodi  Mahasiswa  Lakilaki  Perempuan
0  1       Informatika         50        30         20
1  2  Sistem Informasi         55        30         25
2  3      Teknik Sipil         40        30         10

In [8]:
df[['Prodi', 'Mahasiswa']]

Prodi  Mahasiswa
0       Informatika         50
1  Sistem Informasi         55
2      Teknik Sipil         40

In [9]:
df.iloc[1:3,:]

No             Prodi  Mahasiswa  Lakilaki  Perempuan
1  2  Sistem Informasi         55        30         25
2  3      Teknik Sipil         40        30         10

In [10]:
import numpy as np
myMatrix = np.array([[100, 200, 300], [700, 600, 500], [900, 1000, 800]])
print(myMatrix)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]


In [13]:
transposed_matrix = list(map(list, zip(*myMatrix)))
print(transposed_matrix)

[[100, 700, 900], [200, 600, 1000], [300, 500, 800]]


In [11]:
print(type(myMatrix))

<class 'numpy.ndarray'>
